# stitched area
x_range = {min = "35 mm", max = "60 mm"}
y_range = {min = "35 mm", max = "60 mm"}
z_range = {min = "-4 um",  max = "4.1 um"}
z_step  = "4 um"
strip_overlap = 0.01

# raster scan
bidirectional_scanning = true
line_width = "1.5 mm"
pixel_size = "0.5 Î¼m"
fill_fraction = 0.90
lines_per_buffer = 2000
