# stitched area
x_range = {min = "35 mm", max = "60 mm"}
y_range = {min = "35 mm", max = "60 mm"}
z_range = {min = "-10 um",  max = "10.1 um"}
z_step  = "10 um"
strip_overlap = 0.02

# raster scan
bidirectional_scanning = true
line_width = "1.0 mm"
pixel_size = "0.5 Î¼m"
line_duty_cycle = 0.95
lines_per_buffer = 2000
