bidirectional_scanning = true
line_width = "1.0 mm"
pixel_size = "1.0 Î¼m"
line_duty_cycle = 0.95
buffers_per_acquisition = 20
buffers_allocated = 4 # is there a point to allowing this to be adjustable? could it be auto calculated?
digitizer_profile = "default" # set number of channels
lines_per_buffer = 500