channels = [
    {enabled=true,  inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
    {enabled=true,  inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
    {enabled=false, inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
    {enabled=false, inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
]


[sample_clock]
source = "External"
rate = "100.8 MS/s"
edge = "Rising"


[trigger]
source              = "External"
slope               = "Rising"
external_coupling   = "DC"
external_impedance  = "high"
external_range      = {min="0 V", max="5 V"}