bidirectional_scanning = true
line_width = "1.2 mm"
frame_height = "1.2 mm"
pixel_size = "0.5 Î¼m"
line_duty_cycle = 0.95
frames_per_acquisition = 10

# from old
# fill_fraction = 0.97
# buffers_per_acquisition = 20
# buffers_allocated = 4 # is there a point to allowing this to be adjustable? could it be auto calculated?
# digitizer_profile = "default" # set number of channels


# Fuhrmna
# line_duty_cycle = 0.95
# frames_per_acquisition = 10